version: '3.4'

networks:
  monreseau:
   driver: bridge

services:
  gestiondeslivres:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks: 
        - monreseau

  gestiondeslivres.bd:
    container_name: gestion_des_livres_bd
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - ./containers/database:/var/opt/data
    restart: always
    networks: 
        - monreseau
  